#!/bin/bash
version='0.5.1'
if [[ `uname` == 'Darwin' ]]; then
	platform='darwin'
else
	platform='linux'
fi
if [[ `arch` == 'arm64' ]]; then
	arch='arm64'
else
	arch='amd64'
fi
curl -Lo autocorrect.tar.gz https://github.com/huacnlee/auto-correct.rs/releases/download/v$version/autocorrect-$platform-$arch.tar.gz
tar zxf autocorrect.tar.gz

if [[ `whoami` == 'root' ]]; then
	mv autocorrect /usr/local/bin/autocorrect
else
	sudo mv autocorrect /usr/local/bin/autocorrect
fi
rm autocorrect.tar.gz
