/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LineResult {
  l: number
  c: number
  new: string
  old: string
  severity: number
}
export interface LintResult {
  filepath: string
  lines: Array<LineResult>
  error: string
}
export function format(text: string): string
export function formatFor(text: string, filepath: string): string
export function lintFor(text: string, filepath: string): LintResult
export function loadConfig(configStr: string): void
export function run(args: Array<string>): Promise<void>
export class Ignorer {
  constructor(workDir: string)
  isIgnored(path: string): boolean
}
