newline = ${ "\n" | "\r" }
space = ${ " "+ }

other = ${ !(string) ~ ANY }
comment = ${ single_line_comment | multiple_line_comment }
single_line_comment = _{ "//" ~ (!(newline) ~ ANY)* }
multiple_line_comment = _{ "/*" ~ (!("*/") ~ ANY)* ~ "*/"}

string = ${ 
  ("`" ~ (!("`") ~ ANY)* ~ "`") 
  | ("\"" ~ (!(newline | "\"") ~ ANY)* ~ "\"") 
}
line = _{ string | comment | space | other | newline }
item = _{ SOI ~ line* ~ EOI } 