newline = ${ "\n" | "\r" }
space = ${ " "+ }

other = ${ !(pair) ~ ANY }
comment = ${ single_line_comment | multiline_comment }
single_line_comment = _{ "//" ~ (!(newline) ~ ANY)* }
multiline_comment = _{ "/*" ~ (!("*/") ~ ANY)* ~ "*/"}

string = _{ 
  ("\"" ~ (!(newline | "\"") ~ ANY)* ~ "\"") 
}
key = ${ string ~ (" ")* ~ ":" ~ (" ")* }
value = ${ string  }
pair = _{ key ~ value }

line = _{ pair | comment | space | other | newline }
item = _{ SOI ~ line* ~ EOI } 