newline = ${ "\n" | "\r" }
space = ${ " "+ }

other = ${ !(string) ~ ANY }
comment = ${ single_line_comment | multiline_comment }
single_line_comment = _{ "#" ~ (!(newline) ~ ANY)* }
multiline_comment = _{ "'''" ~ (!("'''") ~ ANY)* ~ "'''"}

string = ${ 
  ("'" ~ (!(newline | "'") ~ ANY)* ~ "'") 
  | ("\"\"\"" ~ (!("\"\"\"") ~ ANY)* ~ "\"\"\""+) 
  | ("\"" ~ (!(newline | "\"") ~ ANY)* ~ "\"") 
}
line = _{ comment | string | space | other | newline }
item = _{ SOI ~ line* ~ EOI } 