newline = ${ "\n" | "\r" }
space = ${ " "+ }

other = ${ !(string) ~ ANY }
comment = ${ single_line_comment | multiline_comment }
single_line_comment = _{ "//" ~ (!(newline) ~ ANY)* }
multiline_comment = _{ "/*" ~ (!("*/") ~ ANY)* ~ "*/"}

string = ${ 
  ("`" ~ (!("`" | string_verb) ~ ANY)* ~ "`") 
  | ("\"" ~ (!(newline | "\"" | string_verb) ~ ANY)* ~ "\"") 
}
string_verb = { "%" ~ ("s" | "q" | "v") }
line = _{ string | comment | space | other | newline }
item = _{ SOI ~ line* ~ EOI } 