newline = ${ "\n" | "\r" }
space = ${ " "+ }

other = ${ !(string) ~ ANY }
comment = ${ single_line_comment | multiline_comment }
single_line_comment = _{ "//" ~ (!(newline) ~ ANY)* }
multiline_comment = _{ "/*" ~ (!("*/") ~ ANY)* ~ "*/"}

string = ${ 
  ("\"" ~ (!(newline | "\"") ~ ANY)* ~ "\"") 
  | ("r" ~ "#"+ ~ "\"" ~ (!("\"#") ~ ANY)* ~ "\"" ~ "#"+) 
}
line = _{ string | comment | space | other | newline }
item = _{ SOI ~ line* ~ EOI } 