item = _{ SOI ~ line* ~ EOI } 
line = _{ include | string | other }

other = ${ !(string) ~ ANY }

WHITESPACE = { " " | "\t" | NEWLINE }

line_comment  = _{ "//" ~ (!(NEWLINE) ~ ANY)* }
block_comment = _{ "/*" ~ (!("*/") ~ ANY)* ~ "*/"}
COMMENT       = ${ line_comment | block_comment }

include = ${ "#include" ~ " "+ ~  inner_string }

string = ${ inner_string }
inner_string = _{ 
  ("\"" ~ (!(NEWLINE | "\"") ~ ANY)* ~ "\"") 
}