item = _{ SOI ~ line* ~ EOI } 
line = _{ para | text | string | other }

other = ${ ANY }

WHITESPACE = @{ " " | "\t" | NEWLINE }

text  = @{ (!para ~ ANY)+ }
string = ${ "{" ~ fn_name* ~ (string_bracket | inner_string) ~ "}" }

string_bracket = ${ "(" ~ string ~ ")" }
inner_string = @{ (!("}" | ")") ~ ANY)*  }

para = ${ function | section }

fn_name = @{ "\\" ~ ASCII_ALPHA+ ~ ("["~ " "* ~"]")* ~ " "* }
function = ${ fn_name ~ (function | string) }

section = @{ "%" ~ (!NEWLINE ~ ANY)+ }